import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Dimensions,
} from 'react-native';
import Feather from 'react-native-vector-icons/Feather';
import LinearGradient from 'react-native-linear-gradient';
import { TrendAnalysisSkeleton } from '../../components/SkeletonLoader';
import { BASE_URL } from '../../utils/config';
import PredictionDetailCard from '../../components/prediction/PredictionDetailCard';
import KeywordCloud from '../../components/ui/KeywordCloud';
import { ROUTES } from '../../navigation/routes';
import { RootStackScreenProps } from '../../navigation/types';
import { Screen } from '../../components/common/Screen';
import Header from '../../components/common/Header';
import { colors } from '../../theme/colors';
import { spacing } from '../../theme/spacing';
import { typography } from '../../theme/typography';

const { width } = Dimensions.get('window');

type Props = RootStackScreenProps<typeof ROUTES.TREND_ANALYSIS>;

export default function TrendAnalysisScreen({ route, navigation }: Props) {
  const item = route.params?.item || { title: "Trend Analysis" };
  const [analysis, setAnalysis] = React.useState<any>(null);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    const fetchAnalysis = async () => {
      try {
        const id = encodeURIComponent(item.trendId || item.id || "");
        const res = await fetch(`${BASE_URL}/api/trends/${id}/analysis`);
        const json = await res.json();
        if (json.success) {
          setAnalysis(json.data);
        }
      } catch (err) {
        console.error("Analysis fetch error:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchAnalysis();
  }, [item]);

  return (
    <Screen scrollable={true} safeAreaEdges={['top']}>
      <Header title="AI Analysis" showBack={true} onBack={() => navigation.goBack()} />

      <View style={styles.scrollContent}>
        {/* TITLE SECTION */}
        <View style={styles.titleSection}>
          <LinearGradient colors={["rgba(106,37,244,0.2)", "rgba(0,198,255,0.05)"]} style={styles.iconRing}>
            <Feather name="cpu" size={32} color={colors.neon.cyan} />
          </LinearGradient>
          <Text style={styles.trendTitle}>{item.title}</Text>
          <Text style={styles.subtitle}>Generated by TrendPulse AI model v4.0</Text>
        </View>

        {loading ? (
          <TrendAnalysisSkeleton />
        ) : analysis ? (
          <>
            {/* METRICS ROW */}
            <View style={styles.metricsRow}>
              <LinearGradient colors={["rgba(34,197,94,0.12)", "rgba(20,15,30,0.8)"]} style={[styles.metricCard, { borderColor: 'rgba(34,197,94,0.2)' }]}>
                <View style={styles.metricHeader}>
                  <View style={[styles.metricIconBg, { backgroundColor: 'rgba(34,197,94,0.2)' }]}>
                    <Feather name="smile" size={16} color={colors.neon.green} />
                  </View>
                  <Text style={styles.metricLabel}>Sentiment</Text>
                </View>
                <Text style={[styles.metricValue, { color: colors.neon.green }]}>{analysis.sentimentScore}% Pos</Text>
                <View style={styles.progressBarBg}>
                  <LinearGradient colors={[colors.neon.green, "#10b981"]} style={[styles.progressBarFill, { width: `${analysis.sentimentScore}%` }]} />
                </View>
              </LinearGradient>

              <LinearGradient colors={["rgba(168,85,247,0.12)", "rgba(20,15,30,0.8)"]} style={[styles.metricCard, { borderColor: 'rgba(168,85,247,0.2)' }]}>
                <View style={styles.metricHeader}>
                  <View style={[styles.metricIconBg, { backgroundColor: 'rgba(168,85,247,0.2)' }]}>
                    <Feather name="trending-up" size={16} color={colors.neon.purple} />
                  </View>
                  <Text style={styles.metricLabel}>Virality</Text>
                </View>
                <Text style={[styles.metricValue, { color: colors.neon.purple }]}>{analysis.viralityScore} <Text style={styles.metricSubValue}>/ 100</Text></Text>
                <View style={styles.progressBarBg}>
                  <LinearGradient colors={[colors.neon.purple, "#d946ef"]} style={[styles.progressBarFill, { width: `${analysis.viralityScore}%` }]} />
                </View>
              </LinearGradient>
            </View>

            {/* KEY DRIVERS */}
            <Text style={styles.sectionHeading}>Key Drivers</Text>
            <View style={styles.glassCard}>
              {analysis.keyDrivers?.map((driver: any, index: number) => (
                <View key={index} style={[styles.driverItem, index === analysis.keyDrivers.length - 1 ? { borderBottomWidth: 0, paddingBottom: 0, marginBottom: 0 } : {}]}>
                  <Feather name={index === 0 ? "zap" : "globe"} size={18} color={index === 0 ? "#eab308" : "#0ea5e9"} style={{ marginTop: 2 }} />
                  <View style={styles.driverTextContainer}>
                    <Text style={styles.driverTitle}>{driver.title}</Text>
                    <Text style={styles.driverDesc}>{driver.desc}</Text>
                  </View>
                </View>
              ))}
            </View>

            {/* WHY TRENDING */}
            {analysis.whyTrending && (
              <>
                <Text style={styles.sectionHeading}>Why It's Trending</Text>
                <View style={styles.glassCard}>
                  <Text style={styles.driverDesc}>{analysis.whyTrending}</Text>
                </View>
              </>
            )}

            {/* PREDICTION */}
            <PredictionDetailCard prediction={{
              confidenceScore: analysis.confidence ? analysis.confidence / 100 : 0.85,
              lifecycleState: analysis.lifecycleState || 'EMERGING',
              predictionJustification: analysis.aiPrediction
            }} />

            {/* KEYWORDS */}
            {analysis.keywords && analysis.keywords.length > 0 && (
              <>
                <Text style={styles.sectionHeading}>Related Keywords</Text>
                <View style={styles.glassCard}>
                  <KeywordCloud keywords={analysis.keywords} onKeywordPress={(kw) => navigation.navigate(ROUTES.MAIN_TABS, { screen: ROUTES.SEARCH, params: { query: kw } })} />
                </View>
              </>
            )}
          </>
        ) : (
          <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', marginTop: 50 }}>
            <Feather name="alert-circle" size={40} color={colors.neon.red} style={{ marginBottom: 16 }} />
            <Text style={{ color: colors.text.primary, fontSize: 16 }}>Failed to load analysis.</Text>
          </View>
        )}

        <TouchableOpacity style={styles.graphBtn} activeOpacity={0.8} onPress={() => navigation.navigate(ROUTES.TREND_GRAPH, { item })}>
          <LinearGradient
            colors={[colors.neon.purple, colors.neon.cyan]}
            start={{ x: 0, y: 0 }}
            end={{ x: 1, y: 0 }}
            style={styles.graphBtnGradient}
          >
            <Feather name="bar-chart-2" size={20} color="#fff" />
            <Text style={styles.graphBtnText}>View Detailed Statistics</Text>
          </LinearGradient>
        </TouchableOpacity>
      </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  titleSection: {
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 30,
  },
  iconRing: {
    width: 70,
    height: 70,
    borderRadius: 35,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(0,198,255,0.3)',
  },
  trendTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.text.primary,
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    color: colors.text.secondary,
    fontSize: 13,
  },
  metricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
  },
  metricCard: {
    width: (width - 55) / 2,
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  metricHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  metricIconBg: {
    padding: 6,
    borderRadius: 8,
    marginRight: 8,
  },
  metricLabel: {
    color: colors.text.secondary,
    fontSize: 14,
    fontWeight: '600',
  },
  metricValue: {
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 12,
  },
  metricSubValue: {
    fontSize: 14,
    color: '#64748b',
    fontWeight: '600',
  },
  progressBarBg: {
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 2,
  },
  sectionHeading: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text.primary,
    marginBottom: 16,
  },
  glassCard: {
    backgroundColor: 'rgba(30,27,46,0.5)',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
    marginBottom: 30,
  },
  driverItem: {
    flexDirection: 'row',
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  driverTextContainer: {
    flex: 1,
    marginLeft: 12,
  },
  driverTitle: {
    color: colors.text.primary,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  driverDesc: {
    color: colors.text.secondary,
    fontSize: 14,
    lineHeight: 20,
  },
  graphBtn: {
    height: 56,
    borderRadius: 28,
    overflow: 'hidden',
    marginTop: 10,
    shadowColor: colors.neon.purple,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 8,
  },
  graphBtnGradient: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  graphBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 10,
  }
});
